Zel2flux 171
RunOnFlux/fluxd pull request #177
Opened 2022-03-11 12:22 UTC by w2vy

This branch has a large number of zel -> flux changes.
The RPCs maintain backwards compatibility
I did not change any file names, so the target builds still create zelcashd etc
I figured that would better be a second step, since that will impact things outside code.

Please look these changes over closely, there may be places I should not have changed, possibly for historical reasons

2022-03-18 16:02 UTC, blondfrogs requested changes
Lets make sure to update those names that i commented on. I didn't comment on all of them but please change them all to the new naming scheme.

2022-03-19 15:05 UTC, blondfrogs requested changes
@w2vy Can we try to use __func__ instead of hardcoding the function name 

`return rebuildfluxnodedb(params, fHelp, "rebuildfluxnodedb");` could be 

`return rebuildfluxnodedb(params, fHelp, __func__);`

2022-03-20 10:53 UTC, w2vy commented
JA>
Looks like we are changing 
/home/main/.flux/determ_zelnodes
to 
/home/main/.flux/determ_fluxnodes
which we can't do if the files already exist, we have to perform a rename if it already exists. 
lets make sure to not rename it, and then we can do the renaming of this folder in a different PR.

TM> It looks like I only did that in one place, fixed

2022-03-22 15:05 UTC, blondfrogs approved these changes

2022-04-04 09:50 UTC, merged

2022-04-13 07:51 UTC, TheTrunk reviewed
@w2vy @blondfrogs please see comments for a quick bug fix

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +    fFluxnode = GetBoolArg("-fluxnode", false);
should be -zelnode

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +        strFluxnodeAddr = GetArg("-fluxnodeaddr", "");
backwards compatilibty for -zelnode

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +                return InitError("Invalid -fluxnodeaddr address: " + strFluxnodeAddr);
backwards compatilibty for -zelnode

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +        std::string strHash = GetArg("-fluxnodeoutpoint", "");
backwards compatilibty for -zelnode

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +        int index = GetArg("-fluxnodeindex", -1);
backwards compatilibty for -zelnode

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +        strFluxnodePrivKey = GetArg("-fluxnodeprivkey", "");
backwards compatilibty for -zelnode

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +             if (FindBenchmarkPath("fluxbenchd", strPath)) {
should be zelbenchd, above we are starting fluxbenchd

2022-04-13 07:51 UTC, TheTrunk commented on src/init.cpp
> +             if (FindBenchmarkPath("fluxbench-cli", strPath)) {
should be zelbench-cli

2022-04-13 07:51 UTC, TheTrunk commented on src/util.cpp
> +    boost::filesystem::path pathConfigFile(GetArg("-znconf", "fluxnode.conf"));
compatilibty for zelnode.conf

2022-04-19 10:40 UTC, w2vy commented on src/init.cpp
> +        strFluxnodePrivKey = GetArg("-fluxnodeprivkey", "");
Should this code look for both zelnodeprivkey and fluxnodeprivkey?
Maybe only using zelnode if fluxnode isn't found?

2022-04-19 10:53 UTC, w2vy commented on src/init.cpp
> +        strFluxnodePrivKey = GetArg("-fluxnodeprivkey", "");
I just reverted the change for now

2022-04-19 10:54 UTC, w2vy commented
I made these changes in zel2flux-171a and will issue a Pull Request