Remove IsDFluxnodeActive calls
RunOnFlux/fluxd pull request #192
Opened 2022-04-29 11:22 UTC by w2vy

Added runtime error if not fFluxnode for good measure, other RPC calls use it too

In non-rpc functions this state was checked directly by block number when examining blocks of any age

2022-05-13 03:13 UTC, TheTrunk requested changes

2022-05-13 03:13 UTC, TheTrunk commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
This rpc can be run on a node that is not a fluxnode

2022-05-13 03:13 UTC, TheTrunk commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
This rpc can be run on a node that is not a fluxnode

2022-05-13 03:13 UTC, TheTrunk commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
This rpc can be run on a node that is not a fluxnode

2022-05-13 03:13 UTC, TheTrunk commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
This rpc can be run on a node that is not a fluxnode

2022-05-13 03:13 UTC, TheTrunk commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
This rpc can be run on a node that is not a fluxnode

2022-05-13 10:35 UTC, w2vy commented on src/rpc/zelnode.cpp
>      if (!fFluxnode) throw runtime_error("This is not a Flux Node");
I think this should be deleted too, this overloaded function is called by getzelnodestatus

2022-05-13 10:42 UTC, w2vy commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
Overloaded function called by listfluxnodeconf and listzelnodeconf, only throw error from listfluxnodeconf wrapper?

2022-05-13 11:19 UTC, w2vy commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
I am taking a fresh look, I want to review the code from before I made changes

2022-05-16 10:47 UTC, w2vy commented on src/rpc/zelnode.cpp
>      if (!fFluxnode) throw runtime_error("This is not a Flux Node");
I reviewed against code before I 'fixed' anything and yes this stays, just wanted to make sure I didn't may a mistake earlier.

2022-05-16 10:48 UTC, w2vy commented on src/rpc/zelnode.cpp
> +    if (!fFluxnode) throw runtime_error("This is not a Flux Node");
Deleted this one too, original code did not have it

2022-05-16 15:29 UTC, TheTrunk commented on src/rpc/zelnode.cpp
>      if (!fFluxnode) throw runtime_error("This is not a Flux Node");
Yes you are correct getfluxnodestatus/getzelnodestatus can only be run on flux node 👍

2022-05-16 15:29 UTC, TheTrunk approved these changes

2022-05-16 18:52 UTC, blondfrogs approved these changes

2022-05-17 02:55 UTC, merged